[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
renderer_check = "Mali-G52"
include = [
    "dEQP-VK.pipeline.blend.*",
    "dEQP-VK.api.buffer_view.*",
    "dEQP-VK.api.copy_and_blit.core.*",
    "dEQP-VK.compute.builtin_var.*",
    "dEQP-VK.draw.renderpass.instanced.draw_indexed_vk_*",
    "dEQP-VK.glsl.builtin.function.integer.usubborrow.*",
    "dEQP-VK.glsl.builtin.precision.frexp.*",
    "dEQP-VK.glsl.builtin.precision.ldexp.*",
    "dEQP-VK.glsl.conversions.*",
    "dEQP-VK.glsl.derivate.*.constant.*",
    "dEQP-VK.glsl.derivate.*.linear.*",
    "dEQP-VK.glsl.derivate.*.uniform_*",
    "dEQP-VK.image.load_store.with_format.*",
    "dEQP-VK.pipeline.sampler.view_type.*.format.r*.address_modes.all_mode_clamp_to_border*",
    "dEQP-VK.ssbo.layout.single_basic_type.*",
]
