.radeonsi-stoney-test:amd64:
  extends:
    - .radeonsi-rules
  variables:
    DEVICE_TYPE: hp-11A-G6-EE-grunt
    DTB: ""
    GPU_VERSION: radeonsi-stoney
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    HWCI_KERNEL_MODULES: amdgpu
    DRIVER_NAME: radeonsi
    FDO_CI_CONCURRENT: 4
    DEQP_EXPECTED_RENDERER: STONEY
    HWCI_FREQ_MAX: "true"
  tags:
    - mesa-ci-x86-64-lava-hp-11A-G6-EE-grunt

radeonsi-stoney-gl:amd64:
  extends:
    - .lava-test:amd64
    - .radeonsi-stoney-test:amd64
  parallel: 5
  variables:
    DEQP_SUITE: radeonsi-stoney

radeonsi-stoney-traces:amd64:
  extends:
    - .lava-piglit-traces:amd64
    - .radeonsi-stoney-test:amd64
  variables:
    EGL_PLATFORM: surfaceless
    PIGLIT_PROFILES: replay
    PIGLIT_JUNIT_RESULTS: 1
    PIGLIT_REPLAY_DESCRIPTION_FILE: "/install/traces-radeonsi.yml"
    PIGLIT_REPLAY_EXTRA_ARGS: --keep-image
  tags:
    - mesa-ci-x86-64-lava-hp-11A-G6-EE-grunt

radeonsi-stoney-piglit-gl:amd64:
  extends:
    - .lava-piglit:amd64
    - .radeonsi-stoney-test:amd64
  variables:
    PIGLIT_FRACTION: 4
    PIGLIT_PLATFORM: mixed_glx_egl
    PIGLIT_PROFILES: quick_gl
    PIGLIT_JUNIT_RESULTS: 1
    HWCI_START_XORG: 1
