.lavapipe-test:
  stage: software-renderer
  extends:
    - .test-vk
    - .lavapipe-rules
    - .deqp-test-vk
  variables:
    GPU_VERSION: lvp
    VK_DRIVER: lvp
    DEQP_EXPECTED_RENDERER: llvmpipe

lavapipe-vk:
  stage: software-renderer
  extends:
    - .lavapipe-test
  variables:
    DEQP_FRACTION: 10

lavapipe-nir-stress:
  extends:
    - .lavapipe-test
  variables:
    DEQP_FRACTION: 100
    NIR_DEBUG: "clone,serialize"

lavapipe-vk-asan:
  extends:
    - .lavapipe-test
  variables:
    GPU_VERSION: lvp-asan
    DEQP_FRACTION: 500
    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.6:libdlclose-skip.so"
  needs:
    - debian/x86_test-vk
    - debian-testing-asan
