.iris-test:
  extends:
    - .lava-test:amd64
    - .iris-rules
  variables:
    DTB: ""
    DRIVER_NAME: iris
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    FLAKES_CHANNEL: "#intel-ci"
  tags:
    - mesa-ci-aarch64-lava-collabora

.iris-apl-test:
  extends:
    - .iris-test
    - .test-manual-mr
  variables:
    DEVICE_TYPE: asus-C523NA-A20057-coral
    GPU_VERSION: iris-apl
    ENV_VARS: "DEQP_EXPECTED_RENDERER=APL"

.iris-glk-test:
  extends:
    - .iris-test
    - .test-manual-mr
  variables:
    DEVICE_TYPE: hp-x360-12b-n4000-octopus
    GPU_VERSION: iris-glk
    ENV_VARS: "DEQP_EXPECTED_RENDERER=GLK"

.iris-amly-test:
  extends:
    - .iris-test
    - .test-manual-mr
  variables:
    DEVICE_TYPE: asus-C433TA-AJ0005-rammus
    GPU_VERSION: iris-amly
    ENV_VARS: "DEQP_EXPECTED_RENDERER=AML"

iris-apl-gles2:
  extends:
    - .iris-apl-test
  variables:
    DEQP_VERSION: gles2

iris-apl-gles3:
  extends:
    - .iris-apl-test
  variables:
    DEQP_VERSION: gles3
    ENV_VARS: "DEQP_EXPECTED_RENDERER=APL DEQP_FRACTION=2"
  parallel: 2

iris-apl-gl:
  extends:
    - .iris-apl-test
  variables:
    DEQP_VERSION: gl46

iris-apl-egl:
  extends:
    - .iris-apl-test
  variables:
    DEQP_VERSION: egl

iris-apl-gles31:
  extends:
    - .iris-apl-test
  variables:
    DEQP_VERSION: gles31
    ENV_VARS: "DEQP_EXPECTED_RENDERER=APL DEQP_FRACTION=2"
  parallel: 2

iris-glk-gles2:
  extends:
    - .iris-glk-test
  variables:
    DEQP_VERSION: gles2

iris-glk-gles3:
  extends:
    - .iris-glk-test
  variables:
    DEQP_VERSION: gles3
    ENV_VARS: "DEQP_EXPECTED_RENDERER=GLK DEQP_FRACTION=4"
  parallel: 2

iris-glk-gles31:
  extends:
    - .iris-glk-test
  variables:
    DEQP_VERSION: gles31
    ENV_VARS: "DEQP_EXPECTED_RENDERER=GLK DEQP_FRACTION=4"
  parallel: 2

iris-glk-gl:
  extends:
    - .iris-glk-test
  variables:
    DEQP_VERSION: gl46

iris-glk-egl:
  extends:
    - .iris-glk-test
  variables:
    DEQP_VERSION: egl

iris-amly-gles2:
  extends:
    - .iris-amly-test
  variables:
    DEQP_VERSION: gles2

iris-amly-gles3:
  extends:
    - .iris-amly-test
  variables:
    DEQP_VERSION: gles3

iris-amly-gles31:
  extends:
    - .iris-amly-test
  variables:
    DEQP_VERSION: gles31

iris-amly-gl:
  extends:
    - .iris-amly-test
  variables:
    DEQP_VERSION: gl46

iris-amly-egl:
  extends:
    - .iris-amly-test
  variables:
    DEQP_VERSION: egl

.iris-traces:
  extends:
    - .lava-piglit-traces:amd64
  variables:
    ENV_VARS: "EGL_PLATFORM=surfaceless PIGLIT_PROFILES=replay PIGLIT_JUNIT_RESULTS=1"

iris-apl-traces:
  extends:
    - .iris-traces
    - .iris-apl-test

iris-glk-traces:
  extends:
    - .iris-traces
    - .iris-glk-test

iris-amly-traces:
  extends:
    - .iris-traces
    - .iris-amly-test
