.iris-traces:amd64:
  extends:
    - .lava-piglit-traces:amd64
    - .iris-rules
  variables:
    ENV_VARS: "EGL_PLATFORM=surfaceless PIGLIT_PROFILES=replay PIGLIT_JUNIT_RESULTS=1"
    DTB: ""
    DRIVER_NAME: iris
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
  tags:
    - mesa-ci-aarch64-lava-collabora

.iris-apl-traces:amd64:
  extends:
    - .iris-traces:amd64
  variables:
    DEVICE_TYPE: asus-C523NA-A20057-coral
    GPU_VERSION: intel-apl

.iris-glk-traces:amd64:
  extends:
    - .iris-traces:amd64
  variables:
    DEVICE_TYPE: hp-x360-12b-n4000-octopus
    GPU_VERSION: intel-glk

.iris-amly-traces:amd64:
  extends:
    - .iris-traces:amd64
  variables:
    DEVICE_TYPE: asus-C433TA-AJ0005-rammus
    GPU_VERSION: intel-amly
