# Basic test set
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
fraction = 3
renderer_check = "Turnip Adreno .* 630"
[deqp.env]
# Force binning in the main run, which makes sure we render at
# least 2 bins.  This is the path that impacts the most different
# features.
TU_DEBUG = "forcebin"

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
include = ["dEQP-VK.renderpass.*"]
prefix = "gmem-"
fraction = 15
[deqp.env]
TU_DEBUG = "nobypass,forcebin"

[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.*"]
prefix = "spill-"
[deqp.env]
IR3_SHADER_DEBUG = "spillall"
