# Basic test set
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
fraction = 100
renderer_check = "Turnip Adreno .* 630"

[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.*"]
prefix = "spill-"
[deqp.env]
IR3_SHADER_DEBUG = "spillall"
