# Manual test rules for using anholt's shared g41.
.anholt-g41-test:
  extends:
    - .crocus-rules
    - .test-gl
    - .test-manual-mr
  tags:
    - anholt-g41
  variables:
    GPU_VERSION: crocus-g41

crocus-g41-deqp:
  extends:
    - .anholt-g41-test
    - .deqp-test
  variables:
    DEQP_SUITE: crocus-g41

crocus-g41-piglit:
  extends:
    - .anholt-g41-test
    - .piglit-test
  variables:
    PIGLIT_PROFILES: gpu
    PIGLIT_PLATFORM: gbm
  artifacts:
    paths:
      - results/
    reports:
      junit: results/junit.xml
  script:
    - install/piglit/piglit-runner.sh

crocus-g41-traces:
  extends:
    - .anholt-g41-test
    - .piglit-traces-test
  variables:
    EGL_PLATFORM: "surfaceless"
    PIGLIT_REPLAY_DESCRIPTION_FILE: "${CI_PROJECT_DIR}/install/traces-crocus-g41.yml"
    PIGLIT_REPLAY_DEVICE_NAME: "crocus-g41"
