.zink-lvp-test:
  extends:
    - .zink-rules
  variables:
    MESA_LOADER_DRIVER_OVERRIDE: "zink"
    ZINK_USE_LAVAPIPE: "true"
    GPU_VERSION: zink-lvp
    # Fix non-conformant llvmpipe filter defaults
    GALLIVM_PERF: "no_filter_hacks"
    LP_NUM_THREADS: 0

zink-piglit-quick_gl:
  extends:
    - .test-gl
    - .piglit-test
    - .zink-lvp-test
  variables:
    PIGLIT_TESTS: >
      -x arb_map_buffer_alignment@arb_map_buffer_alignment-map-invalidate-range
      -x glx-make-current -x arb_timer_query -x arb_sample_shading@builtin-gl-sample-mask
    PIGLIT_PROFILES: quick_gl
    PIGLIT_RESULTS: "zink-quick_gl"

.zink-lvp-deqp-test:
  extends:
    - .test-gl
    - .deqp-test
    - .zink-lvp-test
  variables:
    VK_DRIVER: lvp # Don't move to the top level, piglit runs do funny stuff with VK_DRIVER set
    DEQP_EXPECTED_RENDERER: "zink.*llvmpipe"

zink-lvp-gles2:
  extends:
    - .zink-lvp-deqp-test
  variables:
    DEQP_VER: gles2

zink-lvp-gles3:
  extends:
    - .zink-lvp-deqp-test
  variables:
    DEQP_VER: gles3
    DEQP_FRACTION: 4

zink-lvp-gl:
  extends:
    - .zink-lvp-deqp-test
  variables:
    DEQP_VER: gl32
