[[deqp]]
deqp = "/install/crosvm-runner.sh"
renderer_check = "virgl.*llvmpipe"
version_check = "OpenGL ES 3.2 Mesa $VERSION"
caselists = ["/deqp/mustpass/gles3-master.txt"]
fraction = 1000
deqp_args = [
    "/deqp/modules/gles3/deqp-gles3",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0
