[[deqp]]
deqp = "/install/crosvm-runner.sh"
renderer_check = "virgl.*llvmpipe"
version_check = "OpenGL ES 3.2 Mesa $VERSION"
caselists = ["/deqp/mustpass/gles2-master.txt"]
deqp_args = [
    "/deqp/modules/gles2/deqp-gles2",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0

[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = ["/deqp/mustpass/gles3-master.txt"]
deqp_args = [
    "/deqp/modules/gles3/deqp-gles3",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0

[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = ["/deqp/mustpass/gles31-master.txt"]
deqp_args = [
    "/deqp/modules/gles31/deqp-gles31",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0

[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = [
    "/deqp/mustpass/gl30-master.txt",
    "/deqp/mustpass/gl31-master.txt",
    "/deqp/mustpass/gl32-master.txt",
]
deqp_args = [
    "/deqp/external/openglcts/modules/glcts",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0