.virpipe-test:
  extends:
    - .test-gl
    - .virgl-rules
  variables:
    GALLIVM_PERF: nopt
  script:
    - xvfb-run --server-args='-noreset' sh -c "GALLIUM_DRIVER=virpipe install/deqp-runner.sh"

virpipe-on-gl:
  extends:
    - .deqp-test
    - .virpipe-test
  variables:
    DEQP_SUITE: virpipe-gl
    GPU_VERSION: virpipe-gl
  tags:
    - mesa-swrast
