test-d3d12-windows:
  extends:
    - .build-windows
    - .use-windows_build_vs2019
    - .windows-test-rules
  stage: layered-backends
  dependencies:
    - windows-vs2019
  needs:
    - windows-vs2019
  variables:
    GIT_STRATEGY: none # testing doesn't build anything from source
    GALLIUM_DRIVER: d3d12
    PIGLIT_PROFILE: quick_gl
    PIGLIT_TESTS: -x nv_copy_depth_to_color
  script:
    - . _install/piglit_run.ps1
  artifacts:
    when: on_failure
    name: "mesa_${CI_JOB_NAME}"
    paths:
      - summary/
      - result.txt
